src/webSys/apps/mobile/urls.py
from django.urls import path
from . import  views
urlpatterns = [
    path("mobile/list/", views.mobile_list, name="mobile_list"),

    path("mobile/add/", views.MobileView.as_view(), name="mobile_add"),
    #
    path("mobile/edit/<int:id>/", views.MobileDetailView.as_view(), name="mobile_edit"),
    path("mobile/del/<int:id>/", views.MobileDelete, name="mobile_del"),
]

src/webSys/webSys/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("department.urls")),
    path('', include("employee.urls")),
    path('', include("mobile.urls")),
]

src/webSys/apps/mobile/models.py
import random

from django.db import models

# Create your models here.
class Mobile(models.Model):
    class Meta:
        db_table = "t_mobile"
        verbose_name = "员工"
        verbose_name_plural = verbose_name
    mobile_num = models.CharField(max_length=11, unique=True, verbose_name="手机号")
    price = models.IntegerField(default=0, verbose_name="价格")
    level_choices = (
        (1, "1级"),
        (2, "2级"),
        (3, "3级"),
    )
    level = models.SmallIntegerField(choices=level_choices, default=3, verbose_name="级别")
    status_choices = (
        (0, "未占用"),
        (1, "已占用")
    )
    status = models.SmallIntegerField(choices=status_choices, default=0, verbose_name="状态")

    def generate_data(self):
        for i in range(0, 35):
            self.mobile_num = str(random.randint(135000000000, 189000000000))
            self.price = random.randint(10, 100)
            self.level = random.randint(1, 3)
            self.status = random.randint(0, 1)

src/webSys/apps/mobile/forms.py
from django import  forms
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator

from .models import Mobile


class MobileForm(forms.ModelForm):
    # 字段验证方法1
    # mobile_num = forms.CharField(label="号码", validators=[RegexValidator(r'^135\d{8}$', '需要以135开头')])
    class Meta:
        model = Mobile
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        # super(Form, self).__init__(*args, **kwargs)
        super().__init__(*args, **kwargs)
        # for field in self.fields:
        #     self.fields[field].widget.attrs = {'class': 'form-control'}
        for name, field in self.fields.items():
            field.widget.attrs = {'class': 'form-control', "placeholder": field.label}

    # 字段验证方法2
    def clean_mobile_num(self):
        m = self.cleaned_data["mobile_num"]
        if len(m) != 11:
            raise ValidationError("手机号不合法")

        if Mobile.objects.filter(mobile_num=m).exists():
            raise ValidationError("手机号已存在")
        return  m

class MobileEditForm(forms.ModelForm):
    """
     专用于编辑手机号的Form
    """
    mobile_num = forms.CharField(disabled=True, label="手机号")
    class Meta:
        model = Mobile
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        # super(Form, self).__init__(*args, **kwargs)
        super().__init__(*args, **kwargs)
        # for field in self.fields:
        #     self.fields[field].widget.attrs = {'class': 'form-control'}
        for name, field in self.fields.items():
            field.widget.attrs = {'class': 'form-control', "placeholder": field.label}

    # 字段验证方法2

src/webSys/apps/mobile/views.py
import math

from django.shortcuts import render, redirect

# Create your views here.
from django.utils.safestring import mark_safe
from django.views import View
from mobile.models import Mobile
from .pagination import  Pagination


def mobile_list(request):
    data_dict = {}
    search_data=request.GET.get("q","")
    if search_data:
        data_dict["mobile_num__contains"] = search_data
        data = Mobile.objects.filter(**data_dict).order_by("-level")
        page_object = Pagination(request, data, search_data)  # 其他三个参数根据需求调整
        context = {
            "mobiles": page_object.data,
            "search_data": search_data,
            "page_string": page_object.Html(),
            "search_data": search_data
        }
        return render(request, "mobile/list.html", context)

    data = Mobile.objects.filter(**data_dict).order_by("-level")
    page_object = Pagination(request, data, search_data)  # 其他三个参数根据需求调整
    context = {
        "mobiles": page_object.data,
        "search_data": search_data,
        "page_string": page_object.Html(),
        "search_data": search_data
    }
    return render(request, "mobile/list.html",context)


from .forms import  MobileForm,MobileEditForm
class  MobileView(View):
    def get(self, request):
        form = MobileForm()
        return render(request, "mobile/add.html", {"form": form})
    def post(self, request):
        form = MobileForm(data=request.POST)
        if form.is_valid():
            # print(form.cleaned_data)
            form.save()
            return redirect("/mobile/list/")
        else:
            print(form.errors)
            return render(request, "mobile/add.html", {"form": form})

class MobileDetailView(View):
    def get(self, request, id):
        employee = Mobile.objects.get(id=id)
        form = MobileEditForm(instance=employee)
        return render(request, 'mobile/edit.html', {"form": form})

    def post(self, request, id):
        e = Mobile.objects.get(id=id)
        form = MobileEditForm(data=request.POST, instance=e)  # 更新
        if form.is_valid():
            # form.instance.xx = xxx # 用于设置额外的字段
            form.save()
            return redirect("/mobile/list/")
        else:
            return render(request, 'mobile/edit.html', {"form": form})

def MobileDelete(request, id):
    employee = Mobile.objects.get(id=id)
    employee.delete()
    return redirect("/mobile/list/")

src/webSys/templates/mobile/add.html
{% extends 'base.html' %}
{% block title %}部门管理{% endblock %}

{% block nav-3 %}active{% endblock %}

{% block main%}
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">添加手机号</h3>
    </div>
    <div class="panel-body">
      <div class="col-lg-1"></div>
      <div class="col-lg-9">
        <form class="form-horizontal" method="post" action="/mobile/add/"  novalidate >
          {% csrf_token %}

          {% for field in form %}
          <div class="form-group">
            <label  class="col-sm-2 control-label">{{field.label}}</label>
            <div class="col-sm-10">
              {{ field }}
              <span style="color: red">{{ field.errors.0 }}</span>
            </div>
          </div>
          {% endfor %}
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-primary">添加</button>
            </div>
          </div>
        </form>
      </div>
      <div class="col-lg-2"></div>
    </div>
  </div>
</div>
{% endblock %}

src/webSys/templates/mobile/addform.html
{% extends 'base.html' %}
{% block title %}部门管理{% endblock %}

{% block nav-2 %}active{% endblock %}

{% block main%}
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">添加员工ModelForm</h3>
    </div>
    <div class="panel-body">
      <div class="col-lg-1"></div>
      <div class="col-lg-9">
        <form class="form-horizontal" method="post" novalidate action="/employee/addform/" return="false">
          {% csrf_token %}

          {% for field in form %}
          <div class="form-group">
            <label  class="col-sm-2 control-label">{{field.label}}</label>
            <div class="col-sm-10">
              {{ field }}
              <span style="color: red">{{ field.errors.0 }}</span>
            </div>
          </div>
          {% endfor %}

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-primary">添加</button>
            </div>
          </div>
        </form>
      </div>
      <div class="col-lg-2"></div>
    </div>
  </div>
</div>
{% endblock %}

src/webSys/templates/mobile/edit.html
{% extends 'base.html' %}
{% block title %}部门管理{% endblock %}

{% block nav-3 %}active{% endblock %}

{% block main%}
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">编辑手机号</h3>
    </div>
    <div class="panel-body">
      <div class="col-lg-1"></div>
      <div class="col-lg-9">
        <form class="form-horizontal" method="post" novalidate>
          {% csrf_token %}
          {% for field in form %}
          <div class="form-group">
            <label  class="col-sm-2 control-label">{{field.label}}</label>
            <div class="col-sm-10">
              {{ field }}
              <span style="color: red">{{ field.errors.0 }}</span>
            </div>
          </div>
          {% endfor %}
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-primary">更改</button>
            </div>
          </div>
        </form>
      </div>
      <div class="col-lg-2"></div>
    </div>
  </div>
</div>
{% endblock %}

src/webSys/templates/mobile/list.html
{% extends 'base.html' %}
{% block title %}靓号管理{% endblock %}
{% block nav-3 %}active{% endblock %}

{% block main%}
<div class="container">
<div class="bs-example" data-example-id="panel-without-body-with-table">
    <div class="panel panel-default">
      <!-- Default panel contents -->

      <div class="panel-heading">
        <div class="row">
          <div class="col-lg-2">
            <div class="input-group">
              <i class=" glyphicon glyphicon-th-list" style="margin-right: 6px"></i>
                <a class="btn btn-primary" href="/mobile/add/">添加手机号</a>
            </div><!-- /input-group -->
          </div><!-- /.col-lg-6 -->
          <div class="col-lg-2">
            <form method="GET">
              <div class="input-group">
              <input type="text" class="form-control"    name="q" placeholder="过滤手机号" value="{{search_data}}">
              <span class="input-group-btn">
                <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
              </span>
            </div><!-- /input-group -->
            </form>
          </div><!-- /.col-lg-6 -->
          <div class="col-lg-6">
            <div class="input-group">
            </div><!-- /input-group -->
          </div><!-- /.col-lg-6 -->
        </div><!-- /.row -->
      </div>

      <!-- Table -->
      <table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>手机号</th>
            <th>价格</th>
            <th>级别</th>
            <th>状态</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
        {%  for mobile in mobiles %}
          <tr>
            <th scope="row">{{mobile.id}}</th>
            <td>{{mobile.mobile_num}}</td>
            <td>{{mobile.price }}</td>
            <td>{{ mobile.get_level_display }}</td>
            <td>{{mobile.get_status_display}}</td>
            <td>
                <a class="btn btn-info btn-sm" href="/mobile/edit/{{ mobile.id }}/" >编辑</a>
                <a class="btn btn-danger btn-sm" href="/mobile/del/{{ mobile.id }}/">删除</a>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>

  <div style="margin-top: 5px;text-align: center">
  <nav aria-label="...">
     <ul class="pagination">
          {{ page_string }}
     </ul>
</nav>
  </div>
  </div>
</div>
{% endblock %}