src/webSys/apps/employee/urls.py
from django.urls import path
from . import  views
urlpatterns = [
    path("employee/list/", views.employee_list, name="employee_list"),
    path("employee/add/", views.EmployeeView.as_view(), name="employee_add"),

    path("employee/addform/", views.EmployeeFormView.as_view(), name="employee_addform"),

    path("employee/edit/<int:id>/", views.EmployeeDetailView.as_view(), name="employee_edit"),
    path("employee/del/<int:id>/", views.EmployeeDelete, name="department_del"),
]

src/webSys/webSys/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("department.urls")),
    path('', include("employee.urls")),
    path('', include("mobile.urls")),
]

src/webSys/apps/employee/models.py
import datetime

from django.db import models

# Create your models here.

from department.models import  Department, Base

class Employee(Base):
    """ 员工表 """
    class Meta:
        db_table = "t_employee"
        verbose_name = "员工"
        verbose_name_plural = verbose_name
    name = models.CharField(max_length=32, verbose_name="姓名")
    password = models.CharField(max_length=32, verbose_name="密码")
    age = models.IntegerField(default=1, verbose_name="年龄")
    sex_choices = ((0, "女"), (1, "男"))
    gender = models.SmallIntegerField(choices=sex_choices, default=0, verbose_name="性别")
    salary = models.DecimalField(max_digits=10, decimal_places=2, default=0, verbose_name="薪资")
    offer_at = models.DateField(default=datetime.datetime.now, verbose_name="入职时间")
    department = models.ForeignKey(to=Department, to_field="id", related_name="employee", on_delete=models.CASCADE, verbose_name="部门")

    def __str__(self):
        return f"<{self.name}:{self.gender}:{self.age}>"

src/webSys/apps/employee/views.py
from django.shortcuts import render, redirect

# Create your views here.
from employee.models import Employee
from department.models import Department

def employee_list(request):
    employees = Employee.objects.all()
    return render(request, 'employee/list.html', {"employees": employees})

from django.views import  View
class EmployeeView(View):
    def get(self, request):
        content = {
            "sex_choices": Employee.sex_choices,
            "departments": Department.objects.all()
        }
        return render(request, "employee/add.html", content)

    def post(self, request):
        name = request.POST.get("name")
        password = request.POST.get("password")
        age = request.POST.get("age")
        gender = request.POST.get("gender")
        salary = request.POST.get("salary")
        department = Department.objects.get(id=request.POST.get("department_id"))

        Employee.objects.create(name=name,password=password, age=age, salary=salary, department=department)

        return redirect("/employee/list/")

from django import  forms
class Form(forms.ModelForm):
    name = forms.CharField(min_length=3, max_length=32, error_messages={
            'min_length':'用户名最小需大于3个字符','max_length':'用户名最大需小于32个字符',
            'required':'用户名不能为空'	}
            )
    class Meta:
        model = Employee
        fields = ['name', 'password', 'age', 'gender', 'salary', 'department', 'offer_at']
        # widgets = {
        #     "name": forms.TextInput(attrs={'class': 'form-control'}),
        #     "age": forms.TextInput(attrs={'class': 'form-control'}),
        # }
    def __init__(self, *args, **kwargs):
        # super(Form, self).__init__(*args, **kwargs)
        super().__init__(*args, **kwargs)
        # for field in self.fields:
        #     self.fields[field].widget.attrs = {'class': 'form-control'}
        for name, field in self.fields.items():
            field.widget.attrs = {'class': 'form-control', "placeholder": field.label}

class  EmployeeFormView(View):
    def get(self, request):
        form = Form()
        return render(request, "employee/addform.html", {"form": form})
    def post(self, request):
        form = Form(data=request.POST)
        if form.is_valid():
            # print(form.cleaned_data)
            form.save()
            return redirect("/employee/list/")
        else:
            print(form.errors)
            return render(request, "employee/addform.html", {"form": form})

class EmployeeDetailView(View):
    def get(self, request, id):
        employee = Employee.objects.get(id=id)
        form = Form(instance=employee)
        return render(request, 'employee/edit.html', {"form": form})

    def post(self, request, id):
        e = Employee.objects.get(id=id)
        form = Form(data=request.POST, instance=e) # 更新
        if form.is_valid():
          # form.instance.xx = xxx # 用于设置额外的字段
          form.save()
          return  redirect("/employee/list/")
        else:
            return render(request, 'employee/edit.html', {"form": form})

def EmployeeDelete(request, id):
    employee = Employee.objects.get(id=id)
    employee.delete()
    return  redirect("/employee/list/")

src/webSys/templates/employee/add.html
{% extends 'base.html' %}
{% block title %}部门管理{% endblock %}

{% block nav-2 %}active{% endblock %}

{% block main%}
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">添加员工</h3>
    </div>
    <div class="panel-body">
      <div class="col-lg-1"></div>
      <div class="col-lg-9">
        <form class="form-horizontal" method="post" action="/employee/add/" return="false">
          {% csrf_token %}

          <div class="form-group">
            <label  class="col-sm-2 control-label">姓名</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" name="name" placeholder="">
            </div>
          </div>
          <div class="form-group">
            <label  class="col-sm-2 control-label">密码</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" name="password" placeholder="">
            </div>
          </div>
          <div class="form-group">
            <label  class="col-sm-2 control-label">年龄</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" name="age" placeholder="">
            </div>
          </div>
          <div class="form-group">
            <label  class="col-sm-2 control-label">性别</label>
            <div class="col-sm-10">
              <select class="form-control" name="gender">
                {% for sex in  sex_choices %}
                <option value="{{sex.0}}">{{sex.1}}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="form-group">
            <label  class="col-sm-2 control-label">薪资</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" name="salary" placeholder="">
            </div>
          </div>
          <div class="form-group">
            <label  class="col-sm-2 control-label">部门</label>
            <div class="col-sm-10">
             <select class="form-control" name="department_id">
                {% for department in  departments %}
                <option value="{{department.id}}">{{department.name}}</option>
                {% endfor %}
              </select>
            </div>

          </div>
                    <div class="form-group">
            <label  class="col-sm-2 control-label">sss</label>
            <div class="col-sm-10" id="time-box">
              <input type="text" class="form-control">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-10">
              <label  class="col-sm-2 control-label"></label>
              <span style="color: red; font-size: 18px">{{ msg }}</span>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-primary">添加</button>
            </div>
          </div>
        </form>
      </div>
      <div class="col-lg-2"></div>
    </div>
  </div>
</div>
{% endblock %}

{% block js%}
<script>
  $('#time-box input').datepicker({
    language: "zh-CN",//配置中文
    autoclose: true,//自动关闭
    format: "yyyy-mm-dd"//日期显示格式
});
</script>
{% endblock %}

src/webSys/templates/employee/addform.html
{% extends 'base.html' %}
{% block title %}部门管理{% endblock %}

{% block nav-2 %}active{% endblock %}

{% block main%}
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">添加员工ModelForm</h3>
    </div>
    <div class="panel-body">
      <div class="col-lg-1"></div>
      <div class="col-lg-9">
        <form class="form-horizontal" method="post" novalidate action="/employee/addform/" return="false">
          {% csrf_token %}

          {% for field in form %}
          <div class="form-group">
            <label  class="col-sm-2 control-label">{{field.label}}</label>
            <div class="col-sm-10">
              {{ field }}
              <span style="color: red">{{ field.errors.0 }}</span>
            </div>
          </div>
          {% endfor %}



          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-primary">添加</button>
            </div>
          </div>
        </form>
      </div>
      <div class="col-lg-2"></div>
    </div>
  </div>
</div>
{% endblock %}

{% block js%}
<script>
  $('#id_offer_at').datepicker({
    language: "zh-CN",//配置中文
    autoclose: true,//自动关闭
    format: "yyyy-mm-dd"//日期显示格式
});
</script>
{% endblock %}

src/webSys/templates/employee/edit.html
{% extends 'base.html' %}
{% block title %}部门管理{% endblock %}

{% block nav-2 %}active{% endblock %}

{% block main%}
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">编辑员工</h3>
    </div>
    <div class="panel-body">
      <div class="col-lg-1"></div>
      <div class="col-lg-9">
        <form class="form-horizontal" method="post" novalidate  return="false">
          {% csrf_token %}
          {% for field in form %}
          <div class="form-group">
            <label  class="col-sm-2 control-label">{{field.label}}</label>
            <div class="col-sm-10">
              {{ field }}
              <span style="color: red">{{ field.errors.0 }}</span>
            </div>
          </div>
          {% endfor %}
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-primary">更改</button>
            </div>
          </div>
        </form>
      </div>
      <div class="col-lg-2"></div>
    </div>
  </div>
</div>
{% endblock %}

src/webSys/templates/employee/list.html
{% extends 'base.html' %}
{% block title %}员工管理{% endblock %}
{% block nav-2 %}active{% endblock %}

{% block main%}
<div class="container">
<div class="bs-example" data-example-id="panel-without-body-with-table">
    <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading"><i class=" glyphicon glyphicon-th-list" style="margin-right: 6px"></i>
        <a class="btn btn-primary" href="/employee/add/">添加员工</a>
        <a class="btn btn-primary" href="/employee/addform/">添加员工ModelForm</a>
      </div>

      <!-- Table -->
      <table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>姓名</th>
            <th>年龄</th>
            <th>性别</th>
            <th>薪资</th>
            <th>入职时间</th>
            <th>部门</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
        {%  for employee in employees %}
          <tr>
            <th scope="row">{{employee.id}}</th>
            <td>{{employee.name}}</td>
            <td>{{employee.age }}</td>
            <td>{{ employee.get_gender_display }}</td>
            <td>{{employee.salary}}</td>
            <td>{{employee.created_at | date:"Y-m-d"}}</td>
             <td>{{employee.department}}</td>
            <td>
                <a class="btn btn-info btn-sm" href="/employee/edit/{{ employee.id }}/" >编辑</a>
                <a class="btn btn-danger btn-sm" href="/employee/del/{{ employee.id }}/">删除</a>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}